[FIX] install: Pinned less@3.0.4
Version 3.5.1 latest currently is failing compiling
lessc /home/odoo/odoo-11.0/addons/web/static/lib/bootstrap/less/carousel.less --no-js --no-color --include-path=/home/odoo/odoo-11.0/addons/web/static/lib/bootstrap/less
The output is
The "--no-js" argument is deprecated, as inline JavaScript is disabled by default. Use "--js" to enable inline JavaScript (not recommended).
ParseError: Unrecognised input in /home/odoo/odoo-11.0/addons/web/static/lib/bootstrap/less/carousel.less on line 204, column 28:
203     // set alpha transparency for the best results possible.
204     background-color: #000 \9; // IE8
205     background-color: rgba(0,0,0,0); // IE9